### ISSUE TITLE
JAR build would be appriciated

### ISSUE THREAD

**Issue by GaidamakUA** [twofortyfouram/android-plugin-client-sdk-for-locale#3]
Some of our team members uses Eclipse. And It would be nice if you made jar builds for your libraries, so I won't have to include a lot of source code to our project to make your library run on Eclipse.

**Comment by ccjernigan** [comment]
Great suggestion.  Unfortunately, I think using Eclipse is going to unfortunately require copying and pasting.

The old Eclipse versions of our plug-in examples, [Toast](http://www.244.am/developer/toast.zip) and [Display](http://www.244.am/developer/display.zip), contained all of the code necessary to be a plug-in.  There was no SDK.  Every plug-in contained its own copy of the code necessary.  This was not ideal because it made rebasing plug-in implementations on our latest changes very difficult.  However this approach was intentional because we needed Android resources that the JAR format does not support.

Going forward we are relying on the AAR format and Gradle to provide Android resources, Manifest placeholders, proguard-consumer.txt, transitive dependencies, and other features.  There's no way to provide that with a JAR.

While we could create an uber-JAR using Jar Jar Links to mitigate the need for transitive dependencies, that still leaves the issue of resources, Manifest entries, ProGuard directives, etc.  I don't see the value of using Jar Jar given the amount of manual work that would remain.  We also at one point used a "reflective" way of accessing resources to make that less painful with JARs, however that broke with resource optimization provided by [DexGuard](https://www.guardsquare.com) and was fidgety with `shrinkResources true` provided by the Android Gradle plugin.

Given all of that, I see the options available to you are:
- Use the old examples.
- Migrate to Gradle.
- Use the new examples, but extract the JARs, resources, manifest entries, and transitive dependencies manually.  This means downloading the [AAR](https://bintray.com/artifact/download/twofortyfouram/maven/com/twofortyfouram/android-plugin-client-sdk-for-locale/4.0.0/android-plugin-client-sdk-for-locale-4.0.0.aar) from Bintray, unzipping it, and copying the various elements into your project.  You'll also need to follow the transitive dependencies in the [POM](https://bintray.com/artifact/download/twofortyfouram/maven/com/twofortyfouram/android-plugin-client-sdk-for-locale/4.0.0/android-plugin-client-sdk-for-locale-4.0.0.pom) and do the same thing.

**Comment by GaidamakUA** [comment]
Thank you for reply. I chose last option. But with this case there are one more reason for our team members to migrate to Gradle.
