### ISSUE TITLE
Can't implement AppCompatDelegate while extending AbstractLocalePluginActivity

### ISSUE THREAD

**Issue by ddykhoff** [twofortyfouram/android-plugin-client-sdk-for-locale#4]
public final class EditActivity extends AbstractLocalePluginActivity implements AppCompatDelegate {
...
}

'onPostCreate(Bundle)' in 'com.twofortyfouram.locale.sdk.client.ui.activity.AbstractPluginActivity' clashes with 'onPostCreate(Bundle)' in 'android.support.v7.app.AppCompatDelegate'; attempting to assign weaker access privileges ('protected'); was 'public'

AppCompatDelegate is needed for maintaining material design within Locale plugins and cannot be implemented due to this issue.

**Comment by ccjernigan** [comment]
Thank you for reporting this!  Method visibility on Activity is a little inconsistent, especially with `onCreate` being protected but `onPostCreate` being public.

We've published android-plugin-client-sdk 4.0.1 to resolve this.

Note that we are not fixing the exact issue as reported.  The class AbstractLocalePluginActivity was removed from the SDK in version 3.0.  The example plug-ins, as of December 19, 2015, point to an earlier SDK version which still includes that class.  The example plug-ins will be updated to reflect this, but the exact timing varies.  Changes to the examples are non-atomic with major version changes to the SDK, because they live in different git repos and require prior publishing of the SDK artifact.

Anyone can still consume the newer version of the SDK right away by changing the version number for android-plugin-client-sdk in gradle.properties in the plug-in.  We use semantic versioning for SDK versions, which implies that revving from 2.x to 3.x to 4.x breaks compile time compatibility.

**Comment by ddykhoff** [comment]
You're right, I was using the outdated example. Glad to see that AppCompat is supported in the latest version of the SDK. 

My issue would have been fixed simply by updating my SDK, but I'm glad I help you find an issue! Thanks for the quick response on this.
